### ISSUE TITLE
komga

### ISSUE THREAD

**Issue by kesurof** [laster13/patxav#25]
à l'installation de Komga, un dossier "books" est créé sous /home/local avec comme propriétaire root 

il faut modifier cela afin de créer le dossier avec comme propriétaire l'user.

**Comment by zarevskaya** [comment]
Merci!

**Comment by kesurof** [comment]
Résolu, j'ai modifié le chemin.

Le dossier books n'est plus créé automatiquement, vous avez accès à l'arborescence des dossiers depuis /home/user

**Comment by zarevskaya** [comment]
Excellent! Avec Laster13 ça nous a occupé un peu cette histoire ;)
