### ISSUE TITLE
INFO SSL CERTIFICAT

### ISSUE THREAD

**Issue by barto95100** [laster13/patxav#3]
Bonjour,

petite question comment faire pour ajouter un certificat SSL a la solution Seedbox avec traefik + let's encrypt ? 

Merci pour votre script il fonctionne très bien :)

**Comment by laster13** [comment]
Bonjour,

Traefik se charge automatiquement de la création des certificats, il suffit juste de rajouter le sous domaine concerné auprès du Registrar; si vous confiez la gestion des DNS à clouflare ce sont alors des certificats wildcard qui sont créés

**Comment by barto95100** [comment]
Ok car j'ai fait l'install j'ai un wildcard sous ovh vers mon ip public et pourtant je suis pas en https.. 
:(

**Comment by laster13** [comment]
Dans ta zone DNS tu dois avoir quelque chose comme ça (exemple chez Gandi)

@ | A | 10800 | IP_SERVEUR
-- | -- | -- | --
plex | CNAME | 10800 | domain§.tld.
-- | -- | -- | --

Est ce le cas?

**Comment by barto95100** [comment]
non j'ai un enregistrement de Type A : 

*.domain.tld = @ip_public

et le wildcard fonctionne bien avec un nslokup / dig

**Comment by laster13** [comment]
tu dois configurer tes DNS comme je te le mentionne plus haut et ne pas impliquer ton wildcard perso dans l'install. Si tu viens sur mondedie.fr en te faisant connaitre je te donnerai l'adresse de mon discord. On est environ une 20aine qui pourront t'aider. Poste sur le lien que je t'ai donné plus haut
