### ISSUE TITLE
integrate pihole

### ISSUE THREAD

**Issue by brusezot** [laster13/patxav#6]
Hi,

Very good job, this project is perfect, it's possible to integrate pihole or not ?

**Comment by zarevskaya** [comment]
> 
> 
> Hi,
> 
> Very good job, this project is perfect, it's possible to integrate pihole or not ?

Hi brusezot,

I close the thread beacuse it's not really an issue. 

For any question and discuss about Script Seedbox Docker, join us on Discord: https://discord.gg/v5dZHB5

Have a nice day! :)
